
name: OpenWrt-CI

on:
  push:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_openwrt:
    name: Build OpenWrt Firmware
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk             gettext libncurses5-dev libssl-dev python3-distutils             rsync unzip zlib1g-dev file wget git time

      - name: Prepare Workspace
        run: |
          sudo mkdir -p /mnt/workspace
          sudo rsync -a --delete ./ /mnt/workspace/

      - name: Cache DL packages
        uses: actions/cache@v4
        with:
          path: /mnt/workspace/dl
          key: dl-${{ runner.os }}-${{ hashFiles('feeds.conf.default') }}
          restore-keys: dl-${{ runner.os }}-

      - name: Cache Toolchain Output
        uses: actions/cache@v4
        with:
          path: |
            /mnt/workspace/staging_dir
            /mnt/workspace/build_dir/host
          key: toolchain-${{ runner.os }}-${{ hashFiles('openwrt-ci.yml') }}
          restore-keys: toolchain-${{ runner.os }}-

      - name: Add Custom Plugins
        run: |
          cd /mnt/workspace
          cd package
          git clone https://github.com/jerrykuku/luci-app-argon-config.git
          git clone https://github.com/nikkinikki-org/OpenWrt-nikki.git
          git clone https://github.com/tty228/luci-app-wechatpush.git

      - name: Update Feeds
        run: |
          cd /mnt/workspace
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate Configuration File
        run: |
          cd /mnt/workspace
          rm -f ./.config*
          touch .config
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_PACKAGE_6in4=y
          # CONFIG_PACKAGE_autocore-x86 is not set
          # CONFIG_PACKAGE_automount is not set
          # CONFIG_PACKAGE_autosamba is not set
          CONFIG_PACKAGE_bash=y
          # CONFIG_PACKAGE_bc is not set
          CONFIG_PACKAGE_chinadns-ng=y
          CONFIG_PACKAGE_coreutils-nohup=y
          CONFIG_PACKAGE_ddns-go=y
          # CONFIG_PACKAGE_etherwake is not set
          # CONFIG_PACKAGE_ethtool is not set
          CONFIG_PACKAGE_filebrowser=y
          CONFIG_PACKAGE_firewall=m
          CONFIG_PACKAGE_firewall4=y
          CONFIG_PACKAGE_geoview=y
          CONFIG_PACKAGE_haproxy=y
          CONFIG_PACKAGE_ipt2socks=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=m
          CONFIG_PACKAGE_iptables-mod-fullconenat=m
          CONFIG_PACKAGE_iputils-arping=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_jansson=y
          # CONFIG_PACKAGE_kmod-crypto-ccm is not set
          # CONFIG_PACKAGE_kmod-crypto-cmac is not set
          # CONFIG_PACKAGE_kmod-crypto-des is not set
          # CONFIG_PACKAGE_kmod-crypto-md4 is not set
          # CONFIG_PACKAGE_kmod-crypto-md5 is not set
          # CONFIG_PACKAGE_kmod-crypto-sha256 is not set
          # CONFIG_PACKAGE_kmod-fs-exfat is not set
          # CONFIG_PACKAGE_kmod-fs-ext4 is not set
          # CONFIG_PACKAGE_kmod-fs-ksmbd is not set
          # CONFIG_PACKAGE_kmod-fs-ntfs3 is not set
          CONFIG_PACKAGE_kmod-inet-diag=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=m
          CONFIG_PACKAGE_kmod-ipt-fullconenat=m
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          # CONFIG_PACKAGE_kmod-lib-crc16 is not set
          CONFIG_PACKAGE_kmod-netlink-diag=y
          # CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
          CONFIG_PACKAGE_kmod-nf-socket=y
          CONFIG_PACKAGE_kmod-nft-core=y
          CONFIG_PACKAGE_kmod-nft-fib=y
          CONFIG_PACKAGE_kmod-nft-fullcone=y
          CONFIG_PACKAGE_kmod-nft-nat=y
          CONFIG_PACKAGE_kmod-nft-offload=y
          CONFIG_PACKAGE_kmod-nft-socket=y
          CONFIG_PACKAGE_kmod-nft-tproxy=y
          # CONFIG_PACKAGE_kmod-oid-registry is not set
          # CONFIG_PACKAGE_kmod-scsi-core is not set
          CONFIG_PACKAGE_kmod-sit=y
          # CONFIG_PACKAGE_kmod-usb-storage is not set
          # CONFIG_PACKAGE_kmod-usb-storage-extras is not set
          # CONFIG_PACKAGE_kmod-usb-storage-uas is not set
          # CONFIG_PACKAGE_ksmbd-server is not set
          CONFIG_PACKAGE_libatomic=y
          CONFIG_PACKAGE_libgmp=y
          CONFIG_PACKAGE_libiconv-full=y
          # CONFIG_PACKAGE_libkmod is not set
          CONFIG_PACKAGE_libltdl=y
          CONFIG_PACKAGE_liblua5.3=y
          CONFIG_PACKAGE_libnftnl=y
          # CONFIG_PACKAGE_libnl-core is not set
          # CONFIG_PACKAGE_libnl-genl is not set
          # CONFIG_PACKAGE_libpci is not set
          CONFIG_PACKAGE_libruby=y
          CONFIG_PACKAGE_libyaml=y
          # CONFIG_PACKAGE_luci-app-accesscontrol is not set
          CONFIG_PACKAGE_luci-app-argon-config=y
          # CONFIG_PACKAGE_luci-app-ddns is not set
          CONFIG_PACKAGE_luci-app-ddns-go=y
          CONFIG_PACKAGE_luci-app-filebrowser=y
          # CONFIG_PACKAGE_luci-app-filetransfer is not set
          # CONFIG_PACKAGE_luci-app-ksmbd is not set
          CONFIG_PACKAGE_luci-app-mosdns=y
          CONFIG_PACKAGE_luci-app-nikki=y
          # CONFIG_PACKAGE_luci-app-nlbwmon is not set
          CONFIG_PACKAGE_luci-app-openclash=y
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Geoview=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
          CONFIG_PACKAGE_luci-app-passwall_Nftables_Transparent_Proxy=y
          CONFIG_PACKAGE_luci-app-softethervpn=y
          # CONFIG_PACKAGE_luci-app-vsftpd is not set
          CONFIG_PACKAGE_luci-app-wechatpush=y
          # CONFIG_PACKAGE_luci-app-wol is not set
          CONFIG_PACKAGE_luci-i18n-argon-config-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-ddns-go-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-filebrowser-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mosdns-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-nikki-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-softethervpn-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-wechatpush-zh-cn=y
          # CONFIG_PACKAGE_luci-lib-fs is not set
          CONFIG_PACKAGE_luci-theme-argon=y
          CONFIG_PACKAGE_nftables-json=y
          CONFIG_PACKAGE_nikki=y
          # CONFIG_PACKAGE_nlbwmon is not set
          # CONFIG_PACKAGE_pciids is not set
          # CONFIG_PACKAGE_pciutils is not set
          CONFIG_PACKAGE_ruby=y
          CONFIG_PACKAGE_ruby-bigdecimal=y
          CONFIG_PACKAGE_ruby-date=y
          CONFIG_PACKAGE_ruby-digest=y
          CONFIG_PACKAGE_ruby-enc=y
          CONFIG_PACKAGE_ruby-pstore=y
          CONFIG_PACKAGE_ruby-psych=y
          CONFIG_PACKAGE_ruby-stringio=y
          CONFIG_PACKAGE_ruby-yaml=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
          CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
          CONFIG_PACKAGE_sing-box=y
          CONFIG_PACKAGE_softethervpn5-bridge=y
          CONFIG_PACKAGE_softethervpn5-client=y
          CONFIG_PACKAGE_softethervpn5-libs=y
          CONFIG_PACKAGE_softethervpn5-server=y
          CONFIG_PACKAGE_unzip=y
          CONFIG_PACKAGE_v2dat=y
          CONFIG_PACKAGE_v2ray-geoip=y
          CONFIG_PACKAGE_v2ray-geosite=y
          CONFIG_PACKAGE_v2ray-plugin=y
          # CONFIG_PACKAGE_vsftpd-alt is not set
          # CONFIG_PACKAGE_wsdd2 is not set
          CONFIG_PACKAGE_yq=y
          CONFIG_RUBY_ENABLE_YJIT=y
          CONFIG_SING_BOX_BUILD_ACME=y
          CONFIG_SING_BOX_BUILD_CLASH_API=y
          CONFIG_SING_BOX_BUILD_GVISOR=y
          CONFIG_SING_BOX_BUILD_QUIC=y
          CONFIG_SING_BOX_BUILD_TAILSCALE=y
          CONFIG_SING_BOX_BUILD_UTLS=y
          CONFIG_SING_BOX_BUILD_WIREGUARD=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=800

          EOF
          sed -i 's/^[ 	]*//g' ./.config
          make defconfig

      - name: Download Sources
        run: |
          cd /mnt/workspace
          make download -j$(nproc)

      - name: Compile Firmware
        run: |
          cd /mnt/workspace
          make -j$(nproc)

      - name: Cleanup Temporary Files
        run: |
          cd /mnt/workspace
          rm -rf build_dir tmp staging_dir

      - name: Prepare Artifact
        run: |
          cd /mnt/workspace
          mkdir -p ./artifact/firmware
          cp -rf $(find ./bin/targets/ -type f -name "*.img" -o -name "*.gz" -o -name "*.bin") ./artifact/firmware/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: /mnt/workspace/artifact/firmware/
